/*
 * Copyright (c) 2008-2016, GigaSpaces Technologies, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated By:JavaCC: Do not edit this line. SqlParserConstants.java */
package com.j_spaces.jdbc;

public interface SqlParserConstants {

    int EOF = 0;
    int ALTER = 5;
    int ADD = 6;
    int ALL = 7;
    int AND = 8;
    int ASC = 9;
    int AVG = 10;
    int BETWEEN = 11;
    int BY = 12;
    int CREATE = 13;
    int CALL = 14;
    int DROP = 15;
    int DEFAULT_NULL = 16;
    int DESC = 17;
    int DISTINCT = 18;
    int END = 19;
    int FROM = 20;
    int GROUP = 21;
    int IN = 22;
    int IS = 23;
    int LIKE = 24;
    int RLIKE = 25;
    int MAX = 26;
    int MIN = 27;
    int NOT = 28;
    int NULL = 29;
    int OR = 30;
    int ORDER = 31;
    int SELECT = 32;
    int SUBSTR = 33;
    int SUM = 34;
    int SYSDATE = 35;
    int UPPER = 36;
    int WHERE = 37;
    int COUNT = 38;
    int DELETE = 39;
    int EXCEPTION = 40;
    int ROWNUM = 41;
    int INDEX = 42;
    int INSERT = 43;
    int INTO = 44;
    int SET = 45;
    int TABLE = 46;
    int TO_CHAR = 47;
    int TO_NUMBER = 48;
    int FOR_UPDATE = 49;
    int UPDATE = 50;
    int UNION = 51;
    int VALUES = 52;
    int COMMIT = 53;
    int ROLLBACK = 54;
    int PRIMARY_KEY = 55;
    int UID = 56;
    int USING = 57;
    int DATE = 58;
    int DATETIME = 59;
    int TIME = 60;
    int FLOAT = 61;
    int DOUBLE = 62;
    int NUMBER = 63;
    int DECIMAL = 64;
    int BOOLEAN = 65;
    int INTEGER = 66;
    int VARCHAR = 67;
    int VARCHAR2 = 68;
    int CHAR = 69;
    int LONG = 70;
    int CLOB = 71;
    int BLOB = 72;
    int EMPTY_CLOB = 73;
    int EMPTY_BLOB = 74;
    int LOB = 75;
    int TRUE = 76;
    int FALSE = 77;
    int INT = 78;
    int TIMESTAMP = 79;
    int LONGVARCHAR = 80;
    int TINYINT = 81;
    int SMALLINT = 82;
    int BIGINT = 83;
    int BIT = 84;
    int IDENTIFIER = 85;
    int LETTER = 86;
    int DIGIT = 87;
    int INTEGER_LITERAL = 88;
    int LONG_LITERAL = 89;
    int FLOATING_POINT_LITERAL = 90;
    int EXPONENT = 91;
    int STRING_LITERAL = 92;
    int DATE_LITERAL = 93;
    int ASSIGN = 94;
    int CONCAT = 95;
    int SEMICOLON = 96;
    int DOT = 97;
    int ROWTYPE = 98;
    int TILDE = 99;
    int LESS = 100;
    int LESSEQUAL = 101;
    int GREATER = 102;
    int GREATEREQUAL = 103;
    int EQUAL = 104;
    int NOTEQUAL = 105;
    int NOTEQUAL2 = 106;
    int JOINPLUS = 107;
    int OPENPAREN = 108;
    int CLOSEPAREN = 109;
    int ASTERISK = 110;
    int SLASH = 111;
    int PLUS = 112;
    int MINUS = 113;
    int QUESTIONMARK = 114;
    int OPENBRAKET = 115;
    int CLOSEBRAKET = 116;

    int DEFAULT = 0;

    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\n\"",
            "\"\\r\"",
            "\"\\t\"",
            "\"alter\"",
            "\"add\"",
            "\"all\"",
            "\"and\"",
            "\"asc\"",
            "\"avg\"",
            "\"between\"",
            "\"by\"",
            "\"create\"",
            "\"call\"",
            "\"drop\"",
            "\"default null\"",
            "\"desc\"",
            "\"distinct\"",
            "\"end\"",
            "\"from\"",
            "\"group\"",
            "\"in\"",
            "\"is\"",
            "\"like\"",
            "\"rlike\"",
            "\"max\"",
            "\"min\"",
            "\"not\"",
            "\"null\"",
            "\"or\"",
            "\"order\"",
            "\"select\"",
            "\"substr\"",
            "\"sum\"",
            "\"sysdate\"",
            "\"upper\"",
            "\"where\"",
            "\"count\"",
            "\"delete\"",
            "\"exception\"",
            "\"rownum\"",
            "\"index\"",
            "\"insert\"",
            "\"into\"",
            "\"set\"",
            "\"table\"",
            "\"to_char\"",
            "\"to_number\"",
            "\"for update\"",
            "\"update\"",
            "\"union\"",
            "\"values\"",
            "\"commit\"",
            "\"rollback\"",
            "\"primary key\"",
            "\"uid\"",
            "\"using\"",
            "\"date\"",
            "\"datetime\"",
            "\"time\"",
            "\"float\"",
            "\"double\"",
            "\"number\"",
            "\"decimal\"",
            "\"boolean\"",
            "\"integer\"",
            "\"varchar\"",
            "\"varchar2\"",
            "\"char\"",
            "\"long\"",
            "\"clob\"",
            "\"blob\"",
            "\"empty_clob()\"",
            "\"empty_blob()\"",
            "\"lob\"",
            "\"true\"",
            "\"false\"",
            "\"int\"",
            "\"timestamp\"",
            "\"longvarchar\"",
            "\"tinyint\"",
            "\"smallint\"",
            "\"bigint\"",
            "\"bit\"",
            "<IDENTIFIER>",
            "<LETTER>",
            "<DIGIT>",
            "<INTEGER_LITERAL>",
            "<LONG_LITERAL>",
            "<FLOATING_POINT_LITERAL>",
            "<EXPONENT>",
            "<STRING_LITERAL>",
            "<DATE_LITERAL>",
            "\":=\"",
            "\"||\"",
            "\";\"",
            "\".\"",
            "\"%ROWTYPE\"",
            "\"~\"",
            "\"<\"",
            "\"<=\"",
            "\">\"",
            "\">=\"",
            "\"=\"",
            "\"!=\"",
            "\"<>\"",
            "\"(+)\"",
            "\"(\"",
            "\")\"",
            "\"*\"",
            "\"/\"",
            "\"+\"",
            "\"-\"",
            "\"?\"",
            "\"{\"",
            "\"}\"",
            "\",\"",
            "\"$\"",
    };

}
