/*
 * Copyright (c) 2008-2016, GigaSpaces Technologies, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.gigaspaces.internal.cluster.node.impl.packets.data;

import java.io.Externalizable;

/**
 * A possible fix for a {@link IReplicationPacketDataConsumer#consume(String,
 * IReplicationPacketData, com.gigaspaces.internal.cluster.manager.handlers.IReplicationInFacade)}
 * invocation that returned an error result denoted by a {@link IDataConsumeResult} that its {@link
 * IDataConsumeResult#isFailed()} is true. A fix should be generated by the {@link
 * IReplicationPacketDataProducer} that generated the {@link IReplicationPacketData} that caused an
 * error while consuming
 *
 * @author eitany
 * @since 8.0
 */
public interface IDataConsumeFix extends Externalizable {

}
