/*
 * Copyright (c) 2008-2016, GigaSpaces Technologies, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated By:JavaCC: Do not edit this line. SqlParserTokenManager.java */
package com.j_spaces.jdbc.parser.grammar;

/**
 * Token Manager.
 */
@com.gigaspaces.api.InternalApi
public class SqlParserTokenManager implements SqlParserConstants {

    /**
     * Debug output.
     */
    public java.io.PrintStream debugStream = System.out;

    /**
     * Set debug output.
     */
    public void setDebugStream(java.io.PrintStream ds) {
        debugStream = ds;
    }

    private int jjStopAtPos(int pos, int kind) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        return pos + 1;
    }

    private int jjMoveStringLiteralDfa0_0() {
        switch (curChar) {
            case 9:
                jjmatchedKind = 4;
                return jjMoveNfa_0(0, 0);
            case 10:
                jjmatchedKind = 2;
                return jjMoveNfa_0(0, 0);
            case 13:
                jjmatchedKind = 3;
                return jjMoveNfa_0(0, 0);
            case 32:
                jjmatchedKind = 1;
                return jjMoveNfa_0(0, 0);
            case 33:
                return jjMoveStringLiteralDfa1_0(0x0L, 0x400000000000L);
            case 36:
                jjmatchedKind = 126;
                return jjMoveNfa_0(0, 0);
            case 37:
                return jjMoveStringLiteralDfa1_0(0x0L, 0x8000000000L);
            case 40:
                jjmatchedKind = 113;
                return jjMoveStringLiteralDfa1_0(0x0L, 0x1000000000000L);
            case 41:
                jjmatchedKind = 114;
                return jjMoveNfa_0(0, 0);
            case 42:
                jjmatchedKind = 117;
                return jjMoveNfa_0(0, 0);
            case 43:
                jjmatchedKind = 119;
                return jjMoveNfa_0(0, 0);
            case 44:
                jjmatchedKind = 125;
                return jjMoveNfa_0(0, 0);
            case 45:
                jjmatchedKind = 120;
                return jjMoveNfa_0(0, 0);
            case 46:
                jjmatchedKind = 102;
                return jjMoveNfa_0(0, 0);
            case 47:
                jjmatchedKind = 118;
                return jjMoveNfa_0(0, 0);
            case 58:
                return jjMoveStringLiteralDfa1_0(0x0L, 0x800000000L);
            case 59:
                jjmatchedKind = 101;
                return jjMoveNfa_0(0, 0);
            case 60:
                jjmatchedKind = 105;
                return jjMoveStringLiteralDfa1_0(0x0L, 0x840000000000L);
            case 61:
                jjmatchedKind = 109;
                return jjMoveNfa_0(0, 0);
            case 62:
                jjmatchedKind = 107;
                return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000000L);
            case 63:
                jjmatchedKind = 121;
                return jjMoveNfa_0(0, 0);
            case 65:
                return jjMoveStringLiteralDfa1_0(0x1000000000007e0L, 0x0L);
            case 66:
                return jjMoveStringLiteralDfa1_0(0x1800L, 0xc00810L);
            case 67:
                return jjMoveStringLiteralDfa1_0(0x4002000006000L, 0x500L);
            case 68:
                return jjMoveStringLiteralDfa1_0(0x1800004000078000L, 0x5L);
            case 69:
                return jjMoveStringLiteralDfa1_0(0x8000080000L, 0x3000L);
            case 70:
                return jjMoveStringLiteralDfa1_0(0x4000400000100000L, 0x10000L);
            case 71:
                return jjMoveStringLiteralDfa1_0(0x200000L, 0x0L);
            case 73:
                return jjMoveStringLiteralDfa1_0(0xe0000c00000L, 0x20020L);
            case 76:
                return jjMoveStringLiteralDfa1_0(0x1000000L, 0x84200L);
            case 77:
                return jjMoveStringLiteralDfa1_0(0xc000000L, 0x0L);
            case 78:
                return jjMoveStringLiteralDfa1_0(0x600000030000000L, 0xaL);
            case 79:
                return jjMoveStringLiteralDfa1_0(0xc0000000L, 0x0L);
            case 80:
                return jjMoveStringLiteralDfa1_0(0x30000000000000L, 0x0L);
            case 82:
                return jjMoveStringLiteralDfa1_0(0x8008010002000000L, 0x0L);
            case 83:
                return jjMoveStringLiteralDfa1_0(0x100f00000000L, 0x200000L);
            case 84:
                return jjMoveStringLiteralDfa1_0(0x2000200000000000L, 0x148000L);
            case 85:
                return jjMoveStringLiteralDfa1_0(0xc1800000000000L, 0x0L);
            case 86:
                return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0xc0L);
            case 87:
                return jjMoveStringLiteralDfa1_0(0x1000000000L, 0x0L);
            case 91:
                jjmatchedKind = 115;
                return jjMoveStringLiteralDfa1_0(0x0L, 0x1000000000000000L);
            case 93:
                jjmatchedKind = 116;
                return jjMoveNfa_0(0, 0);
            case 97:
                return jjMoveStringLiteralDfa1_0(0x1000000000007e0L, 0x0L);
            case 98:
                return jjMoveStringLiteralDfa1_0(0x1800L, 0xc00810L);
            case 99:
                return jjMoveStringLiteralDfa1_0(0x4002000006000L, 0x500L);
            case 100:
                return jjMoveStringLiteralDfa1_0(0x1800004000078000L, 0x5L);
            case 101:
                return jjMoveStringLiteralDfa1_0(0x8000080000L, 0x3000L);
            case 102:
                return jjMoveStringLiteralDfa1_0(0x4000400000100000L, 0x10000L);
            case 103:
                return jjMoveStringLiteralDfa1_0(0x200000L, 0x0L);
            case 105:
                return jjMoveStringLiteralDfa1_0(0xe0000c00000L, 0x20020L);
            case 108:
                return jjMoveStringLiteralDfa1_0(0x1000000L, 0x84200L);
            case 109:
                return jjMoveStringLiteralDfa1_0(0xc000000L, 0x0L);
            case 110:
                return jjMoveStringLiteralDfa1_0(0x600000030000000L, 0xaL);
            case 111:
                return jjMoveStringLiteralDfa1_0(0xc0000000L, 0x0L);
            case 112:
                return jjMoveStringLiteralDfa1_0(0x30000000000000L, 0x0L);
            case 114:
                return jjMoveStringLiteralDfa1_0(0x8008010002000000L, 0x0L);
            case 115:
                return jjMoveStringLiteralDfa1_0(0x100f00000000L, 0x200000L);
            case 116:
                return jjMoveStringLiteralDfa1_0(0x2000200000000000L, 0x148000L);
            case 117:
                return jjMoveStringLiteralDfa1_0(0xc1800000000000L, 0x0L);
            case 118:
                return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0xc0L);
            case 119:
                return jjMoveStringLiteralDfa1_0(0x1000000000L, 0x0L);
            case 123:
                jjmatchedKind = 122;
                return jjMoveNfa_0(0, 0);
            case 124:
                return jjMoveStringLiteralDfa1_0(0x0L, 0x1000000000L);
            case 125:
                jjmatchedKind = 123;
                return jjMoveNfa_0(0, 0);
            case 126:
                jjmatchedKind = 104;
                return jjMoveNfa_0(0, 0);
            default:
                return jjMoveNfa_0(0, 0);
        }
    }

    private int jjMoveStringLiteralDfa1_0(long active0, long active1) {
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return jjMoveNfa_0(0, 0);
        }
        switch (curChar) {
            case 42:
                return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1000000000000000L);
            case 43:
                return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1000000000000L);
            case 61:
                if ((active1 & 0x800000000L) != 0L) {
                    jjmatchedKind = 99;
                    jjmatchedPos = 1;
                } else if ((active1 & 0x40000000000L) != 0L) {
                    jjmatchedKind = 106;
                    jjmatchedPos = 1;
                } else if ((active1 & 0x100000000000L) != 0L) {
                    jjmatchedKind = 108;
                    jjmatchedPos = 1;
                } else if ((active1 & 0x400000000000L) != 0L) {
                    jjmatchedKind = 110;
                    jjmatchedPos = 1;
                }
                break;
            case 62:
                if ((active1 & 0x800000000000L) != 0L) {
                    jjmatchedKind = 111;
                    jjmatchedPos = 1;
                }
                break;
            case 65:
                return jjMoveStringLiteralDfa2_0(active0, 0x1822200004004000L, active1, 0x100c0L);
            case 68:
                return jjMoveStringLiteralDfa2_0(active0, 0x40L, active1, 0L);
            case 69:
                return jjMoveStringLiteralDfa2_0(active0, 0x8000104100030800L, active1, 0x4L);
            case 72:
                return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L, active1, 0x100L);
            case 73:
                return jjMoveStringLiteralDfa2_0(active0, 0x2040000009040000L, active1, 0xd40000L);
            case 76:
                return jjMoveStringLiteralDfa2_0(active0, 0x40000000020000a0L, active1, 0xc00L);
            case 77:
                return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x203000L);
            case 78:
                if ((active0 & 0x400000L) != 0L) {
                    jjmatchedKind = 22;
                    jjmatchedPos = 1;
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x10e0000080100L, active1, 0x20020L);
            case 79:
                return jjMoveStringLiteralDfa2_0(active0, 0xc412010000000L, active1, 0x84211L);
            case 80:
                return jjMoveStringLiteralDfa2_0(active0, 0x800000000000L, active1, 0L);
            case 82:
                if ((active0 & 0x40000000L) != 0L) {
                    jjmatchedKind = 30;
                    jjmatchedPos = 1;
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x1000008030a000L, active1, 0x8000008000L);
            case 83:
                if ((active0 & 0x800000L) != 0L) {
                    jjmatchedKind = 23;
                    jjmatchedPos = 1;
                } else if ((active0 & 0x100000000000000L) != 0L) {
                    jjmatchedKind = 56;
                    jjmatchedPos = 1;
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x80000000000200L, active1, 0L);
            case 85:
                return jjMoveStringLiteralDfa2_0(active0, 0x600000620000000L, active1, 0xaL);
            case 86:
                return jjMoveStringLiteralDfa2_0(active0, 0x400L, active1, 0L);
            case 88:
                return jjMoveStringLiteralDfa2_0(active0, 0x8000000000L, active1, 0L);
            case 89:
                if ((active0 & 0x1000L) != 0L) {
                    jjmatchedKind = 12;
                    jjmatchedPos = 1;
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x800000000L, active1, 0L);
            case 97:
                return jjMoveStringLiteralDfa2_0(active0, 0x1822200004004000L, active1, 0x100c0L);
            case 100:
                return jjMoveStringLiteralDfa2_0(active0, 0x40L, active1, 0L);
            case 101:
                return jjMoveStringLiteralDfa2_0(active0, 0x8000104100030800L, active1, 0x4L);
            case 104:
                return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L, active1, 0x100L);
            case 105:
                return jjMoveStringLiteralDfa2_0(active0, 0x2040000009040000L, active1, 0xd40000L);
            case 108:
                return jjMoveStringLiteralDfa2_0(active0, 0x40000000020000a0L, active1, 0xc00L);
            case 109:
                return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x203000L);
            case 110:
                if ((active0 & 0x400000L) != 0L) {
                    jjmatchedKind = 22;
                    jjmatchedPos = 1;
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x10e0000080100L, active1, 0x20020L);
            case 111:
                return jjMoveStringLiteralDfa2_0(active0, 0xc412010000000L, active1, 0x84211L);
            case 112:
                return jjMoveStringLiteralDfa2_0(active0, 0x800000000000L, active1, 0L);
            case 114:
                if ((active0 & 0x40000000L) != 0L) {
                    jjmatchedKind = 30;
                    jjmatchedPos = 1;
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x1000008030a000L, active1, 0x8000L);
            case 115:
                if ((active0 & 0x800000L) != 0L) {
                    jjmatchedKind = 23;
                    jjmatchedPos = 1;
                } else if ((active0 & 0x100000000000000L) != 0L) {
                    jjmatchedKind = 56;
                    jjmatchedPos = 1;
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x80000000000200L, active1, 0L);
            case 117:
                return jjMoveStringLiteralDfa2_0(active0, 0x600000620000000L, active1, 0xaL);
            case 118:
                return jjMoveStringLiteralDfa2_0(active0, 0x400L, active1, 0L);
            case 120:
                return jjMoveStringLiteralDfa2_0(active0, 0x8000000000L, active1, 0L);
            case 121:
                if ((active0 & 0x1000L) != 0L) {
                    jjmatchedKind = 12;
                    jjmatchedPos = 1;
                }
                return jjMoveStringLiteralDfa2_0(active0, 0x800000000L, active1, 0L);
            case 124:
                if ((active1 & 0x1000000000L) != 0L) {
                    jjmatchedKind = 100;
                    jjmatchedPos = 1;
                }
                break;
            default:
                break;
        }
        return jjMoveNfa_0(0, 1);
    }

    private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1) {
        if (((active0 &= old0) | (active1 &= old1)) == 0L)
            return jjMoveNfa_0(0, 1);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return jjMoveNfa_0(0, 1);
        }
        switch (curChar) {
            case 41:
                if ((active1 & 0x1000000000000L) != 0L) {
                    jjmatchedKind = 112;
                    jjmatchedPos = 2;
                }
                break;
            case 65:
                return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000000L, active1, 0x200100L);
            case 66:
                if ((active1 & 0x4000L) != 0L) {
                    jjmatchedKind = 78;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x200200000000L, active1, 0L);
            case 67:
                if ((active0 & 0x200L) != 0L) {
                    jjmatchedKind = 9;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L, active1, 0x4L);
            case 68:
                if ((active0 & 0x40L) != 0L) {
                    jjmatchedKind = 6;
                    jjmatchedPos = 2;
                } else if ((active0 & 0x100L) != 0L) {
                    jjmatchedKind = 8;
                    jjmatchedPos = 2;
                } else if ((active0 & 0x80000L) != 0L) {
                    jjmatchedKind = 19;
                    jjmatchedPos = 2;
                } else if ((active0 & 0x40000000000000L) != 0L) {
                    jjmatchedKind = 54;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x820080000000L, active1, 0L);
            case 69:
                return jjMoveStringLiteralDfa3_0(active0, 0x1000002000L, active1, 0L);
            case 70:
                return jjMoveStringLiteralDfa3_0(active0, 0x10000L, active1, 0L);
            case 71:
                if ((active0 & 0x400L) != 0L) {
                    jjmatchedKind = 10;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x400000L);
            case 73:
                return jjMoveStringLiteralDfa3_0(active0, 0x91000002000000L, active1, 0L);
            case 75:
                return jjMoveStringLiteralDfa3_0(active0, 0x1000000L, active1, 0L);
            case 76:
                if ((active0 & 0x80L) != 0L) {
                    jjmatchedKind = 7;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x60a004120004000L, active1, 0x10000L);
            case 77:
                if ((active0 & 0x400000000L) != 0L) {
                    jjmatchedKind = 34;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x2004000000000000L, active1, 0x4000aL);
            case 78:
                if ((active0 & 0x8000000L) != 0L) {
                    jjmatchedKind = 27;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x180200L);
            case 79:
                return jjMoveStringLiteralDfa3_0(active0, 0x4000000000308000L, active1, 0x8000000c10L);
            case 80:
                return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x3000L);
            case 82:
                return jjMoveStringLiteralDfa3_0(active0, 0x20400000000000L, active1, 0xc0L);
            case 83:
                return jjMoveStringLiteralDfa3_0(active0, 0x40800060000L, active1, 0L);
            case 84:
                if ((active0 & 0x10000000L) != 0L) {
                    jjmatchedKind = 28;
                    jjmatchedPos = 2;
                } else if ((active0 & 0x100000000000L) != 0L) {
                    jjmatchedKind = 44;
                    jjmatchedPos = 2;
                } else if ((active1 & 0x20000L) != 0L) {
                    jjmatchedKind = 81;
                    jjmatchedPos = 2;
                } else if ((active1 & 0x800000L) != 0L) {
                    jjmatchedKind = 87;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x1800080000000820L, active1, 0x20L);
            case 85:
                return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L, active1, 0x8001L);
            case 87:
                return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L, active1, 0L);
            case 88:
                if ((active0 & 0x4000000L) != 0L) {
                    jjmatchedKind = 26;
                    jjmatchedPos = 2;
                }
                break;
            case 93:
                if ((active1 & 0x1000000000000000L) != 0L) {
                    jjmatchedKind = 124;
                    jjmatchedPos = 2;
                }
                break;
            case 97:
                return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000000L, active1, 0x200100L);
            case 98:
                if ((active1 & 0x4000L) != 0L) {
                    jjmatchedKind = 78;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x200200000000L, active1, 0L);
            case 99:
                if ((active0 & 0x200L) != 0L) {
                    jjmatchedKind = 9;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L, active1, 0x4L);
            case 100:
                if ((active0 & 0x40L) != 0L) {
                    jjmatchedKind = 6;
                    jjmatchedPos = 2;
                } else if ((active0 & 0x100L) != 0L) {
                    jjmatchedKind = 8;
                    jjmatchedPos = 2;
                } else if ((active0 & 0x80000L) != 0L) {
                    jjmatchedKind = 19;
                    jjmatchedPos = 2;
                } else if ((active0 & 0x40000000000000L) != 0L) {
                    jjmatchedKind = 54;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x820080000000L, active1, 0L);
            case 101:
                return jjMoveStringLiteralDfa3_0(active0, 0x1000002000L, active1, 0L);
            case 102:
                return jjMoveStringLiteralDfa3_0(active0, 0x10000L, active1, 0L);
            case 103:
                if ((active0 & 0x400L) != 0L) {
                    jjmatchedKind = 10;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x400000L);
            case 105:
                return jjMoveStringLiteralDfa3_0(active0, 0x91000002000000L, active1, 0L);
            case 107:
                return jjMoveStringLiteralDfa3_0(active0, 0x1000000L, active1, 0L);
            case 108:
                if ((active0 & 0x80L) != 0L) {
                    jjmatchedKind = 7;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x60a004120004000L, active1, 0x10000L);
            case 109:
                if ((active0 & 0x400000000L) != 0L) {
                    jjmatchedKind = 34;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x2004000000000000L, active1, 0x4000aL);
            case 110:
                if ((active0 & 0x8000000L) != 0L) {
                    jjmatchedKind = 27;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x180200L);
            case 111:
                return jjMoveStringLiteralDfa3_0(active0, 0x4000000000308000L, active1, 0xc10L);
            case 112:
                return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x3000L);
            case 114:
                return jjMoveStringLiteralDfa3_0(active0, 0x20400000000000L, active1, 0xc0L);
            case 115:
                return jjMoveStringLiteralDfa3_0(active0, 0x40800060000L, active1, 0L);
            case 116:
                if ((active0 & 0x10000000L) != 0L) {
                    jjmatchedKind = 28;
                    jjmatchedPos = 2;
                } else if ((active0 & 0x100000000000L) != 0L) {
                    jjmatchedKind = 44;
                    jjmatchedPos = 2;
                } else if ((active1 & 0x20000L) != 0L) {
                    jjmatchedKind = 81;
                    jjmatchedPos = 2;
                } else if ((active1 & 0x800000L) != 0L) {
                    jjmatchedKind = 87;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x1800080000000820L, active1, 0x20L);
            case 117:
                return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L, active1, 0x8001L);
            case 119:
                return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L, active1, 0L);
            case 120:
                if ((active0 & 0x4000000L) != 0L) {
                    jjmatchedKind = 26;
                    jjmatchedPos = 2;
                }
                break;
            default:
                break;
        }
        return jjMoveNfa_0(0, 2);
    }

    private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1) {
        if (((active0 &= old0) | (active1 &= old1)) == 0L)
            return jjMoveNfa_0(0, 2);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return jjMoveNfa_0(0, 2);
        }
        switch (curChar) {
            case 32:
                return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L, active1, 0L);
            case 65:
                return jjMoveStringLiteralDfa4_0(active0, 0x4000800000012000L, active1, 0L);
            case 66:
                if ((active1 & 0x400L) != 0L) {
                    jjmatchedKind = 74;
                    jjmatchedPos = 3;
                } else if ((active1 & 0x800L) != 0L) {
                    jjmatchedKind = 75;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x3L);
            case 67:
                if ((active0 & 0x20000L) != 0L) {
                    jjmatchedKind = 17;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0xc0L);
            case 68:
                return jjMoveStringLiteralDfa4_0(active0, 0x800000000L, active1, 0L);
            case 69:
                if ((active0 & 0x1000000L) != 0L) {
                    jjmatchedKind = 24;
                    jjmatchedPos = 3;
                } else if ((active0 & 0x800000000000000L) != 0L) {
                    jjmatchedKind = 59;
                    jjmatchedPos = 3;
                } else if ((active0 & 0x2000000000000000L) != 0L) {
                    jjmatchedKind = 61;
                    jjmatchedPos = 3;
                } else if ((active1 & 0x8000L) != 0L) {
                    jjmatchedKind = 79;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x100006c180000020L, active1, 0x40028L);
            case 71:
                if ((active1 & 0x200L) != 0L) {
                    jjmatchedKind = 73;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x80000L);
            case 73:
                return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400004L);
            case 75:
                return jjMoveStringLiteralDfa4_0(active0, 0x2000000L, active1, 0L);
            case 76:
                if ((active0 & 0x4000L) != 0L) {
                    jjmatchedKind = 14;
                    jjmatchedPos = 3;
                } else if ((active0 & 0x20000000L) != 0L) {
                    jjmatchedKind = 29;
                    jjmatchedPos = 3;
                } else if ((active0 & 0x8000000000000000L) != 0L) {
                    jjmatchedKind = 63;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x608200000000000L, active1, 0x200010L);
            case 77:
                if ((active0 & 0x100000L) != 0L) {
                    jjmatchedKind = 20;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x14000000000000L, active1, 0L);
            case 78:
                return jjMoveStringLiteralDfa4_0(active0, 0x80012000000000L, active1, 0L);
            case 79:
                if ((active0 & 0x80000000000L) != 0L) {
                    jjmatchedKind = 43;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000L, active1, 0L);
            case 80:
                if ((active0 & 0x8000L) != 0L) {
                    jjmatchedKind = 15;
                    jjmatchedPos = 3;
                }
                break;
            case 82:
                if ((active1 & 0x100L) != 0L) {
                    jjmatchedKind = 72;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L, active1, 0L);
            case 83:
                return jjMoveStringLiteralDfa4_0(active0, 0x200000000L, active1, 0x10000L);
            case 84:
                return jjMoveStringLiteralDfa4_0(active0, 0x20000000040000L, active1, 0x3000L);
            case 85:
                return jjMoveStringLiteralDfa4_0(active0, 0x2000000200000L, active1, 0L);
            case 87:
                return jjMoveStringLiteralDfa4_0(active0, 0x800L, active1, 0x8000000000L);
            case 89:
                return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x100000L);
            case 97:
                return jjMoveStringLiteralDfa4_0(active0, 0x4000800000012000L, active1, 0L);
            case 98:
                if ((active1 & 0x400L) != 0L) {
                    jjmatchedKind = 74;
                    jjmatchedPos = 3;
                } else if ((active1 & 0x800L) != 0L) {
                    jjmatchedKind = 75;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x3L);
            case 99:
                if ((active0 & 0x20000L) != 0L) {
                    jjmatchedKind = 17;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0xc0L);
            case 100:
                return jjMoveStringLiteralDfa4_0(active0, 0x800000000L, active1, 0L);
            case 101:
                if ((active0 & 0x1000000L) != 0L) {
                    jjmatchedKind = 24;
                    jjmatchedPos = 3;
                } else if ((active0 & 0x800000000000000L) != 0L) {
                    jjmatchedKind = 59;
                    jjmatchedPos = 3;
                } else if ((active0 & 0x2000000000000000L) != 0L) {
                    jjmatchedKind = 61;
                    jjmatchedPos = 3;
                } else if ((active1 & 0x8000L) != 0L) {
                    jjmatchedKind = 79;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x100006c180000020L, active1, 0x40028L);
            case 103:
                if ((active1 & 0x200L) != 0L) {
                    jjmatchedKind = 73;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x80000L);
            case 105:
                return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x400004L);
            case 107:
                return jjMoveStringLiteralDfa4_0(active0, 0x2000000L, active1, 0L);
            case 108:
                if ((active0 & 0x4000L) != 0L) {
                    jjmatchedKind = 14;
                    jjmatchedPos = 3;
                } else if ((active0 & 0x20000000L) != 0L) {
                    jjmatchedKind = 29;
                    jjmatchedPos = 3;
                } else if ((active0 & 0x8000000000000000L) != 0L) {
                    jjmatchedKind = 63;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x608200000000000L, active1, 0x200010L);
            case 109:
                if ((active0 & 0x100000L) != 0L) {
                    jjmatchedKind = 20;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x14000000000000L, active1, 0L);
            case 110:
                return jjMoveStringLiteralDfa4_0(active0, 0x80012000000000L, active1, 0L);
            case 111:
                if ((active0 & 0x80000000000L) != 0L) {
                    jjmatchedKind = 43;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000L, active1, 0L);
            case 112:
                if ((active0 & 0x8000L) != 0L) {
                    jjmatchedKind = 15;
                    jjmatchedPos = 3;
                }
                break;
            case 114:
                if ((active1 & 0x100L) != 0L) {
                    jjmatchedKind = 72;
                    jjmatchedPos = 3;
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L, active1, 0L);
            case 115:
                return jjMoveStringLiteralDfa4_0(active0, 0x200000000L, active1, 0x10000L);
            case 116:
                return jjMoveStringLiteralDfa4_0(active0, 0x20000000040000L, active1, 0x3000L);
            case 117:
                return jjMoveStringLiteralDfa4_0(active0, 0x2000000200000L, active1, 0L);
            case 119:
                return jjMoveStringLiteralDfa4_0(active0, 0x800L, active1, 0L);
            case 121:
                return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x100000L);
            default:
                break;
        }
        return jjMoveNfa_0(0, 3);
    }

    private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1) {
        if (((active0 &= old0) | (active1 &= old1)) == 0L)
            return jjMoveNfa_0(0, 3);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return jjMoveNfa_0(0, 3);
        }
        switch (curChar) {
            case 65:
                return jjMoveStringLiteralDfa5_0(active0, 0x10000800000000L, active1, 0L);
            case 66:
                return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L, active1, 0L);
            case 67:
                return jjMoveStringLiteralDfa5_0(active0, 0x100000000L, active1, 0L);
            case 69:
                if ((active0 & 0x2000000L) != 0L) {
                    jjmatchedKind = 25;
                    jjmatchedPos = 4;
                } else if ((active0 & 0x1000000000L) != 0L) {
                    jjmatchedKind = 36;
                    jjmatchedPos = 4;
                } else if ((active0 & 0x200000000000L) != 0L) {
                    jjmatchedKind = 45;
                    jjmatchedPos = 4;
                } else if ((active1 & 0x10000L) != 0L) {
                    jjmatchedKind = 80;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0x2000000000800L, active1, 0x12L);
            case 71:
                if ((active0 & 0x80000000000000L) != 0L) {
                    jjmatchedKind = 55;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x20L);
            case 72:
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0xc0L);
            case 73:
                return jjMoveStringLiteralDfa5_0(active0, 0x24000000040000L, active1, 0x100000L);
            case 76:
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x200001L);
            case 77:
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x4L);
            case 78:
                if ((active0 & 0x1000000000000L) != 0L) {
                    jjmatchedKind = 48;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x400000L);
            case 80:
                if ((active0 & 0x200000L) != 0L) {
                    jjmatchedKind = 21;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L, active1, 0L);
            case 82:
                if ((active0 & 0x20L) != 0L) {
                    jjmatchedKind = 5;
                    jjmatchedPos = 4;
                } else if ((active0 & 0x80000000L) != 0L) {
                    jjmatchedKind = 31;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L, active1, 0x8L);
            case 83:
                return jjMoveStringLiteralDfa5_0(active0, 0x600000000000000L, active1, 0x40000L);
            case 84:
                if ((active0 & 0x2000000000L) != 0L) {
                    jjmatchedKind = 37;
                    jjmatchedPos = 4;
                } else if ((active0 & 0x4000000000000000L) != 0L) {
                    jjmatchedKind = 62;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0x1000804200002000L, active1, 0x8000000000L);
            case 85:
                return jjMoveStringLiteralDfa5_0(active0, 0x410000010000L, active1, 0L);
            case 86:
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x80000L);
            case 88:
                if ((active0 & 0x20000000000L) != 0L) {
                    jjmatchedKind = 41;
                    jjmatchedPos = 4;
                }
                break;
            case 89:
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x3000L);
            case 97:
                return jjMoveStringLiteralDfa5_0(active0, 0x10000800000000L, active1, 0L);
            case 98:
                return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L, active1, 0L);
            case 99:
                return jjMoveStringLiteralDfa5_0(active0, 0x100000000L, active1, 0L);
            case 101:
                if ((active0 & 0x2000000L) != 0L) {
                    jjmatchedKind = 25;
                    jjmatchedPos = 4;
                } else if ((active0 & 0x1000000000L) != 0L) {
                    jjmatchedKind = 36;
                    jjmatchedPos = 4;
                } else if ((active0 & 0x200000000000L) != 0L) {
                    jjmatchedKind = 45;
                    jjmatchedPos = 4;
                } else if ((active1 & 0x10000L) != 0L) {
                    jjmatchedKind = 80;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0x2000000000800L, active1, 0x12L);
            case 103:
                if ((active0 & 0x80000000000000L) != 0L) {
                    jjmatchedKind = 55;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x20L);
            case 104:
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0xc0L);
            case 105:
                return jjMoveStringLiteralDfa5_0(active0, 0x24000000040000L, active1, 0x100000L);
            case 108:
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x200001L);
            case 109:
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x4L);
            case 110:
                if ((active0 & 0x1000000000000L) != 0L) {
                    jjmatchedKind = 48;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x400000L);
            case 112:
                if ((active0 & 0x200000L) != 0L) {
                    jjmatchedKind = 21;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L, active1, 0L);
            case 114:
                if ((active0 & 0x20L) != 0L) {
                    jjmatchedKind = 5;
                    jjmatchedPos = 4;
                } else if ((active0 & 0x80000000L) != 0L) {
                    jjmatchedKind = 31;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L, active1, 0x8L);
            case 115:
                return jjMoveStringLiteralDfa5_0(active0, 0x600000000000000L, active1, 0x40000L);
            case 116:
                if ((active0 & 0x2000000000L) != 0L) {
                    jjmatchedKind = 37;
                    jjmatchedPos = 4;
                } else if ((active0 & 0x4000000000000000L) != 0L) {
                    jjmatchedKind = 62;
                    jjmatchedPos = 4;
                }
                return jjMoveStringLiteralDfa5_0(active0, 0x1000804200002000L, active1, 0L);
            case 117:
                return jjMoveStringLiteralDfa5_0(active0, 0x410000010000L, active1, 0L);
            case 118:
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x80000L);
            case 120:
                if ((active0 & 0x20000000000L) != 0L) {
                    jjmatchedKind = 41;
                    jjmatchedPos = 4;
                }
                break;
            case 121:
                return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x3000L);
            default:
                break;
        }
        return jjMoveNfa_0(0, 4);
    }

    private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1) {
        if (((active0 &= old0) | (active1 &= old1)) == 0L)
            return jjMoveNfa_0(0, 4);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return jjMoveNfa_0(0, 4);
        }
        switch (curChar) {
            case 32:
                return jjMoveStringLiteralDfa6_0(active0, 0x600000000000000L, active1, 0L);
            case 65:
                return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000L, active1, 0x800d4L);
            case 69:
                if ((active0 & 0x2000L) != 0L) {
                    jjmatchedKind = 13;
                    jjmatchedPos = 5;
                } else if ((active0 & 0x4000000000L) != 0L) {
                    jjmatchedKind = 38;
                    jjmatchedPos = 5;
                } else if ((active0 & 0x800000000000L) != 0L) {
                    jjmatchedKind = 47;
                    jjmatchedPos = 5;
                } else if ((active1 & 0x1L) != 0L) {
                    jjmatchedKind = 64;
                    jjmatchedPos = 5;
                }
                return jjMoveStringLiteralDfa6_0(active0, 0x800L, active1, 0x20L);
            case 73:
                return jjMoveStringLiteralDfa6_0(active0, 0x1000000000000000L, active1, 0x200008L);
            case 76:
                return jjMoveStringLiteralDfa6_0(active0, 0x10000L, active1, 0L);
            case 77:
                if ((active0 & 0x10000000000L) != 0L) {
                    jjmatchedKind = 40;
                    jjmatchedPos = 5;
                }
                break;
            case 78:
                return jjMoveStringLiteralDfa6_0(active0, 0x40000L, active1, 0x100000L);
            case 80:
                return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L, active1, 0L);
            case 82:
                if ((active0 & 0x200000000L) != 0L) {
                    jjmatchedKind = 33;
                    jjmatchedPos = 5;
                } else if ((active1 & 0x2L) != 0L) {
                    jjmatchedKind = 65;
                    jjmatchedPos = 5;
                }
                return jjMoveStringLiteralDfa6_0(active0, 0x10000000000000L, active1, 0L);
            case 83:
                if ((active0 & 0x2000000000000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 5;
                }
                break;
            case 84:
                if ((active0 & 0x100000000L) != 0L) {
                    jjmatchedKind = 32;
                    jjmatchedPos = 5;
                } else if ((active0 & 0x40000000000L) != 0L) {
                    jjmatchedKind = 42;
                    jjmatchedPos = 5;
                } else if ((active0 & 0x4000000000000L) != 0L) {
                    jjmatchedKind = 50;
                    jjmatchedPos = 5;
                } else if ((active1 & 0x400000L) != 0L) {
                    jjmatchedKind = 86;
                    jjmatchedPos = 5;
                }
                return jjMoveStringLiteralDfa6_0(active0, 0x20008800000000L, active1, 0x40000L);
            case 89:
                return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x8000000000L);
            case 95:
                return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x3000L);
            case 97:
                return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000L, active1, 0x800d4L);
            case 101:
                if ((active0 & 0x2000L) != 0L) {
                    jjmatchedKind = 13;
                    jjmatchedPos = 5;
                } else if ((active0 & 0x4000000000L) != 0L) {
                    jjmatchedKind = 38;
                    jjmatchedPos = 5;
                } else if ((active0 & 0x800000000000L) != 0L) {
                    jjmatchedKind = 47;
                    jjmatchedPos = 5;
                } else if ((active1 & 0x1L) != 0L) {
                    jjmatchedKind = 64;
                    jjmatchedPos = 5;
                }
                return jjMoveStringLiteralDfa6_0(active0, 0x800L, active1, 0x20L);
            case 105:
                return jjMoveStringLiteralDfa6_0(active0, 0x1000000000000000L, active1, 0x200008L);
            case 108:
                return jjMoveStringLiteralDfa6_0(active0, 0x10000L, active1, 0L);
            case 109:
                if ((active0 & 0x10000000000L) != 0L) {
                    jjmatchedKind = 40;
                    jjmatchedPos = 5;
                }
                break;
            case 110:
                return jjMoveStringLiteralDfa6_0(active0, 0x40000L, active1, 0x100000L);
            case 112:
                return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L, active1, 0L);
            case 114:
                if ((active0 & 0x200000000L) != 0L) {
                    jjmatchedKind = 33;
                    jjmatchedPos = 5;
                } else if ((active1 & 0x2L) != 0L) {
                    jjmatchedKind = 65;
                    jjmatchedPos = 5;
                }
                return jjMoveStringLiteralDfa6_0(active0, 0x10000000000000L, active1, 0L);
            case 115:
                if ((active0 & 0x2000000000000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 5;
                }
                break;
            case 116:
                if ((active0 & 0x100000000L) != 0L) {
                    jjmatchedKind = 32;
                    jjmatchedPos = 5;
                } else if ((active0 & 0x40000000000L) != 0L) {
                    jjmatchedKind = 42;
                    jjmatchedPos = 5;
                } else if ((active0 & 0x4000000000000L) != 0L) {
                    jjmatchedKind = 50;
                    jjmatchedPos = 5;
                } else if ((active1 & 0x400000L) != 0L) {
                    jjmatchedKind = 86;
                    jjmatchedPos = 5;
                }
                return jjMoveStringLiteralDfa6_0(active0, 0x20008800000000L, active1, 0x40000L);
            default:
                break;
        }
        return jjMoveNfa_0(0, 5);
    }

    private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1) {
        if (((active0 &= old0) | (active1 &= old1)) == 0L)
            return jjMoveNfa_0(0, 5);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return jjMoveNfa_0(0, 5);
        }
        switch (curChar) {
            case 65:
                return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x40000L);
            case 66:
                return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x2000L);
            case 67:
                if ((active1 & 0x8L) != 0L) {
                    jjmatchedKind = 67;
                    jjmatchedPos = 6;
                }
                return jjMoveStringLiteralDfa7_0(active0, 0x8000000040000L, active1, 0x1000L);
            case 68:
                return jjMoveStringLiteralDfa7_0(active0, 0x400000000000L, active1, 0L);
            case 69:
                if ((active0 & 0x800000000L) != 0L) {
                    jjmatchedKind = 35;
                    jjmatchedPos = 6;
                }
                break;
            case 70:
                return jjMoveStringLiteralDfa7_0(active0, 0x400000000000000L, active1, 0L);
            case 73:
                return jjMoveStringLiteralDfa7_0(active0, 0x20008000000000L, active1, 0L);
            case 76:
                if ((active1 & 0x4L) != 0L) {
                    jjmatchedKind = 66;
                    jjmatchedPos = 6;
                }
                return jjMoveStringLiteralDfa7_0(active0, 0x200000000000000L, active1, 0L);
            case 77:
                return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000000L, active1, 0L);
            case 78:
                if ((active0 & 0x800L) != 0L) {
                    jjmatchedKind = 11;
                    jjmatchedPos = 6;
                } else if ((active1 & 0x10L) != 0L) {
                    jjmatchedKind = 68;
                    jjmatchedPos = 6;
                }
                return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x200000L);
            case 80:
                return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x8000000000L);
            case 82:
                if ((active1 & 0x20L) != 0L) {
                    jjmatchedKind = 69;
                    jjmatchedPos = 6;
                } else if ((active1 & 0x40L) != 0L) {
                    jjmatchedKind = 70;
                    jjmatchedPos = 6;
                }
                return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x80080L);
            case 84:
                if ((active1 & 0x100000L) != 0L) {
                    jjmatchedKind = 84;
                    jjmatchedPos = 6;
                }
                return jjMoveStringLiteralDfa7_0(active0, 0x10000L, active1, 0L);
            case 89:
                return jjMoveStringLiteralDfa7_0(active0, 0x10000000000000L, active1, 0L);
            case 97:
                return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x40000L);
            case 98:
                return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x2000L);
            case 99:
                if ((active1 & 0x8L) != 0L) {
                    jjmatchedKind = 67;
                    jjmatchedPos = 6;
                }
                return jjMoveStringLiteralDfa7_0(active0, 0x8000000040000L, active1, 0x1000L);
            case 100:
                return jjMoveStringLiteralDfa7_0(active0, 0x400000000000L, active1, 0L);
            case 101:
                if ((active0 & 0x800000000L) != 0L) {
                    jjmatchedKind = 35;
                    jjmatchedPos = 6;
                }
                break;
            case 102:
                return jjMoveStringLiteralDfa7_0(active0, 0x400000000000000L, active1, 0L);
            case 105:
                return jjMoveStringLiteralDfa7_0(active0, 0x20008000000000L, active1, 0L);
            case 108:
                if ((active1 & 0x4L) != 0L) {
                    jjmatchedKind = 66;
                    jjmatchedPos = 6;
                }
                return jjMoveStringLiteralDfa7_0(active0, 0x200000000000000L, active1, 0L);
            case 109:
                return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000000L, active1, 0L);
            case 110:
                if ((active0 & 0x800L) != 0L) {
                    jjmatchedKind = 11;
                    jjmatchedPos = 6;
                } else if ((active1 & 0x10L) != 0L) {
                    jjmatchedKind = 68;
                    jjmatchedPos = 6;
                }
                return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x200000L);
            case 114:
                if ((active1 & 0x20L) != 0L) {
                    jjmatchedKind = 69;
                    jjmatchedPos = 6;
                } else if ((active1 & 0x40L) != 0L) {
                    jjmatchedKind = 70;
                    jjmatchedPos = 6;
                }
                return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x80080L);
            case 116:
                if ((active1 & 0x100000L) != 0L) {
                    jjmatchedKind = 84;
                    jjmatchedPos = 6;
                }
                return jjMoveStringLiteralDfa7_0(active0, 0x10000L, active1, 0L);
            case 121:
                return jjMoveStringLiteralDfa7_0(active0, 0x10000000000000L, active1, 0L);
            default:
                break;
        }
        return jjMoveNfa_0(0, 6);
    }

    private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1) {
        if (((active0 &= old0) | (active1 &= old1)) == 0L)
            return jjMoveNfa_0(0, 6);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return jjMoveNfa_0(0, 6);
        }
        switch (curChar) {
            case 32:
                return jjMoveStringLiteralDfa8_0(active0, 0x10000000010000L, active1, 0L);
            case 50:
                if ((active1 & 0x80L) != 0L) {
                    jjmatchedKind = 71;
                    jjmatchedPos = 7;
                }
                break;
            case 65:
                return jjMoveStringLiteralDfa8_0(active0, 0x200400000000000L, active1, 0L);
            case 67:
                return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x80000L);
            case 69:
                if ((active0 & 0x1000000000000000L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 7;
                } else if ((active1 & 0x8000000000L) != 0L) {
                    jjmatchedKind = 103;
                    jjmatchedPos = 7;
                }
                break;
            case 73:
                return jjMoveStringLiteralDfa8_0(active0, 0x400000000000000L, active1, 0L);
            case 75:
                if ((active0 & 0x8000000000000L) != 0L) {
                    jjmatchedKind = 51;
                    jjmatchedPos = 7;
                }
                break;
            case 76:
                return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x3000L);
            case 77:
                return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x40000L);
            case 79:
                return jjMoveStringLiteralDfa8_0(active0, 0x20008000000000L, active1, 0L);
            case 84:
                if ((active0 & 0x40000L) != 0L) {
                    jjmatchedKind = 18;
                    jjmatchedPos = 7;
                } else if ((active1 & 0x200000L) != 0L) {
                    jjmatchedKind = 85;
                    jjmatchedPos = 7;
                }
                break;
            case 97:
                return jjMoveStringLiteralDfa8_0(active0, 0x200400000000000L, active1, 0L);
            case 99:
                return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x80000L);
            case 101:
                if ((active0 & 0x1000000000000000L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 7;
                }
                break;
            case 105:
                return jjMoveStringLiteralDfa8_0(active0, 0x400000000000000L, active1, 0L);
            case 107:
                if ((active0 & 0x8000000000000L) != 0L) {
                    jjmatchedKind = 51;
                    jjmatchedPos = 7;
                }
                break;
            case 108:
                return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x3000L);
            case 109:
                return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x40000L);
            case 111:
                return jjMoveStringLiteralDfa8_0(active0, 0x20008000000000L, active1, 0L);
            case 116:
                if ((active0 & 0x40000L) != 0L) {
                    jjmatchedKind = 18;
                    jjmatchedPos = 7;
                } else if ((active1 & 0x200000L) != 0L) {
                    jjmatchedKind = 85;
                    jjmatchedPos = 7;
                }
                break;
            default:
                break;
        }
        return jjMoveNfa_0(0, 7);
    }

    private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1) {
        if (((active0 &= old0) | (active1 &= old1)) == 0L)
            return jjMoveNfa_0(0, 7);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return jjMoveNfa_0(0, 7);
        }
        switch (curChar) {
            case 72:
                return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x80000L);
            case 75:
                return jjMoveStringLiteralDfa9_0(active0, 0x10000000000000L, active1, 0L);
            case 78:
                if ((active0 & 0x8000000000L) != 0L) {
                    jjmatchedKind = 39;
                    jjmatchedPos = 8;
                }
                return jjMoveStringLiteralDfa9_0(active0, 0x20000000010000L, active1, 0L);
            case 79:
                return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x3000L);
            case 80:
                if ((active1 & 0x40000L) != 0L) {
                    jjmatchedKind = 82;
                    jjmatchedPos = 8;
                }
                break;
            case 82:
                return jjMoveStringLiteralDfa9_0(active0, 0x400000000000000L, active1, 0L);
            case 83:
                return jjMoveStringLiteralDfa9_0(active0, 0x200000000000000L, active1, 0L);
            case 84:
                return jjMoveStringLiteralDfa9_0(active0, 0x400000000000L, active1, 0L);
            case 104:
                return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x80000L);
            case 107:
                return jjMoveStringLiteralDfa9_0(active0, 0x10000000000000L, active1, 0L);
            case 110:
                if ((active0 & 0x8000000000L) != 0L) {
                    jjmatchedKind = 39;
                    jjmatchedPos = 8;
                }
                return jjMoveStringLiteralDfa9_0(active0, 0x20000000010000L, active1, 0L);
            case 111:
                return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x3000L);
            case 112:
                if ((active1 & 0x40000L) != 0L) {
                    jjmatchedKind = 82;
                    jjmatchedPos = 8;
                }
                break;
            case 114:
                return jjMoveStringLiteralDfa9_0(active0, 0x400000000000000L, active1, 0L);
            case 115:
                return jjMoveStringLiteralDfa9_0(active0, 0x200000000000000L, active1, 0L);
            case 116:
                return jjMoveStringLiteralDfa9_0(active0, 0x400000000000L, active1, 0L);
            default:
                break;
        }
        return jjMoveNfa_0(0, 8);
    }

    private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1) {
        if (((active0 &= old0) | (active1 &= old1)) == 0L)
            return jjMoveNfa_0(0, 8);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return jjMoveNfa_0(0, 8);
        }
        switch (curChar) {
            case 32:
                return jjMoveStringLiteralDfa10_0(active0, 0x20000000000000L, active1, 0L);
            case 65:
                return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x80000L);
            case 66:
                return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x3000L);
            case 69:
                if ((active0 & 0x400000000000L) != 0L) {
                    jjmatchedKind = 46;
                    jjmatchedPos = 9;
                }
                return jjMoveStringLiteralDfa10_0(active0, 0x10000000000000L, active1, 0L);
            case 83:
                return jjMoveStringLiteralDfa10_0(active0, 0x400000000000000L, active1, 0L);
            case 84:
                if ((active0 & 0x200000000000000L) != 0L) {
                    jjmatchedKind = 57;
                    jjmatchedPos = 9;
                }
                break;
            case 85:
                return jjMoveStringLiteralDfa10_0(active0, 0x10000L, active1, 0L);
            case 97:
                return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x80000L);
            case 98:
                return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x3000L);
            case 101:
                if ((active0 & 0x400000000000L) != 0L) {
                    jjmatchedKind = 46;
                    jjmatchedPos = 9;
                }
                return jjMoveStringLiteralDfa10_0(active0, 0x10000000000000L, active1, 0L);
            case 115:
                return jjMoveStringLiteralDfa10_0(active0, 0x400000000000000L, active1, 0L);
            case 116:
                if ((active0 & 0x200000000000000L) != 0L) {
                    jjmatchedKind = 57;
                    jjmatchedPos = 9;
                }
                break;
            case 117:
                return jjMoveStringLiteralDfa10_0(active0, 0x10000L, active1, 0L);
            default:
                break;
        }
        return jjMoveNfa_0(0, 9);
    }

    private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1) {
        if (((active0 &= old0) | (active1 &= old1)) == 0L)
            return jjMoveNfa_0(0, 9);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return jjMoveNfa_0(0, 9);
        }
        switch (curChar) {
            case 40:
                return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x3000L);
            case 66:
                return jjMoveStringLiteralDfa11_0(active0, 0x20000000000000L, active1, 0L);
            case 76:
                return jjMoveStringLiteralDfa11_0(active0, 0x10000L, active1, 0L);
            case 82:
                if ((active1 & 0x80000L) != 0L) {
                    jjmatchedKind = 83;
                    jjmatchedPos = 10;
                }
                break;
            case 84:
                if ((active0 & 0x400000000000000L) != 0L) {
                    jjmatchedKind = 58;
                    jjmatchedPos = 10;
                }
                break;
            case 89:
                if ((active0 & 0x10000000000000L) != 0L) {
                    jjmatchedKind = 52;
                    jjmatchedPos = 10;
                }
                break;
            case 98:
                return jjMoveStringLiteralDfa11_0(active0, 0x20000000000000L, active1, 0L);
            case 108:
                return jjMoveStringLiteralDfa11_0(active0, 0x10000L, active1, 0L);
            case 114:
                if ((active1 & 0x80000L) != 0L) {
                    jjmatchedKind = 83;
                    jjmatchedPos = 10;
                }
                break;
            case 116:
                if ((active0 & 0x400000000000000L) != 0L) {
                    jjmatchedKind = 58;
                    jjmatchedPos = 10;
                }
                break;
            case 121:
                if ((active0 & 0x10000000000000L) != 0L) {
                    jjmatchedKind = 52;
                    jjmatchedPos = 10;
                }
                break;
            default:
                break;
        }
        return jjMoveNfa_0(0, 10);
    }

    private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1) {
        if (((active0 &= old0) | (active1 &= old1)) == 0L)
            return jjMoveNfa_0(0, 10);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return jjMoveNfa_0(0, 10);
        }
        switch (curChar) {
            case 41:
                if ((active1 & 0x1000L) != 0L) {
                    jjmatchedKind = 76;
                    jjmatchedPos = 11;
                } else if ((active1 & 0x2000L) != 0L) {
                    jjmatchedKind = 77;
                    jjmatchedPos = 11;
                }
                break;
            case 76:
                if ((active0 & 0x10000L) != 0L) {
                    jjmatchedKind = 16;
                    jjmatchedPos = 11;
                }
                break;
            case 89:
                if ((active0 & 0x20000000000000L) != 0L) {
                    jjmatchedKind = 53;
                    jjmatchedPos = 11;
                }
                break;
            case 108:
                if ((active0 & 0x10000L) != 0L) {
                    jjmatchedKind = 16;
                    jjmatchedPos = 11;
                }
                break;
            case 121:
                if ((active0 & 0x20000000000000L) != 0L) {
                    jjmatchedKind = 53;
                    jjmatchedPos = 11;
                }
                break;
            default:
                break;
        }
        return jjMoveNfa_0(0, 11);
    }

    static final long[] jjbitVec0 = {
            0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
    };
    static final long[] jjbitVec2 = {
            0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
    };

    private int jjMoveNfa_0(int startState, int curPos) {
        int strKind = jjmatchedKind;
        int strPos = jjmatchedPos;
        int seenUpto;
        input_stream.backup(seenUpto = curPos + 1);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            throw new Error("Internal Error");
        }
        curPos = 0;
        int startsAt = 0;
        jjnewStateCnt = 49;
        int i = 1;
        jjstateSet[0] = startState;
        int kind = 0x7fffffff;
        for (; ; ) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64) {
                long l = 1L << curChar;
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x3ff000000000000L & l) != 0L) {
                                if (kind > 93)
                                    kind = 93;
                                jjCheckNAddStates(0, 8);
                            } else if (curChar == 39)
                                jjCheckNAddStates(9, 12);
                            else if (curChar == 46)
                                jjCheckNAdd(5);
                            break;
                        case 2:
                            if ((0x3ff440000000000L & l) != 0L)
                                jjAddStates(13, 14);
                            break;
                        case 4:
                            if (curChar == 46)
                                jjCheckNAdd(5);
                            break;
                        case 5:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 95)
                                kind = 95;
                            jjCheckNAddTwoStates(5, 6);
                            break;
                        case 7:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(8);
                            break;
                        case 8:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 95)
                                kind = 95;
                            jjCheckNAdd(8);
                            break;
                        case 10:
                            if ((0x3ff440000000000L & l) == 0L)
                                break;
                            if (kind > 88)
                                kind = 88;
                            jjstateSet[jjnewStateCnt++] = 10;
                            break;
                        case 11:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjAddStates(15, 16);
                            break;
                        case 12:
                            if (curChar == 58)
                                jjCheckNAdd(13);
                            break;
                        case 13:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 92)
                                kind = 92;
                            jjCheckNAdd(13);
                            break;
                        case 14:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 93)
                                kind = 93;
                            jjCheckNAddStates(0, 8);
                            break;
                        case 15:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 93)
                                kind = 93;
                            jjCheckNAdd(15);
                            break;
                        case 16:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(16, 17);
                            break;
                        case 18:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(18, 19);
                            break;
                        case 19:
                            if (curChar == 46)
                                jjCheckNAdd(20);
                            break;
                        case 20:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 95)
                                kind = 95;
                            jjCheckNAddTwoStates(20, 21);
                            break;
                        case 22:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(23);
                            break;
                        case 23:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 95)
                                kind = 95;
                            jjCheckNAdd(23);
                            break;
                        case 24:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(24, 25);
                            break;
                        case 26:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(27);
                            break;
                        case 27:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 95)
                                kind = 95;
                            jjCheckNAdd(27);
                            break;
                        case 28:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 95)
                                kind = 95;
                            jjCheckNAddTwoStates(28, 29);
                            break;
                        case 30:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(31);
                            break;
                        case 31:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 95)
                                kind = 95;
                            jjCheckNAdd(31);
                            break;
                        case 32:
                            if (curChar == 39)
                                jjCheckNAddStates(9, 12);
                            break;
                        case 33:
                            if ((0xffffff7fffffffffL & l) != 0L)
                                jjCheckNAddStates(17, 19);
                            break;
                        case 34:
                            if (curChar == 39)
                                jjCheckNAddStates(20, 22);
                            break;
                        case 35:
                            if (curChar == 39)
                                jjstateSet[jjnewStateCnt++] = 34;
                            break;
                        case 36:
                            if ((0xffffff7fffffffffL & l) != 0L)
                                jjCheckNAddStates(20, 22);
                            break;
                        case 37:
                            if (curChar == 39 && kind > 97)
                                kind = 97;
                            break;
                        case 38:
                            if ((0xf000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 39;
                            break;
                        case 39:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 40;
                            break;
                        case 40:
                            if (curChar == 47)
                                jjstateSet[jjnewStateCnt++] = 41;
                            break;
                        case 41:
                            if ((0x3000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 42;
                            break;
                        case 42:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 43;
                            break;
                        case 43:
                            if (curChar == 47)
                                jjstateSet[jjnewStateCnt++] = 44;
                            break;
                        case 44:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 45;
                            break;
                        case 45:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 46;
                            break;
                        case 46:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 47;
                            break;
                        case 47:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 48;
                            break;
                        case 48:
                            if (curChar == 39 && kind > 98)
                                kind = 98;
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 88)
                                    kind = 88;
                                jjCheckNAddStates(23, 25);
                            } else if (curChar == 96)
                                jjstateSet[jjnewStateCnt++] = 1;
                            break;
                        case 1:
                            if ((0x7fffffe87fffffeL & l) != 0L)
                                jjCheckNAddTwoStates(2, 3);
                            break;
                        case 2:
                            if ((0x7ffffff87fffffeL & l) != 0L)
                                jjCheckNAddTwoStates(2, 3);
                            break;
                        case 3:
                            if (curChar == 96 && kind > 89)
                                kind = 89;
                            break;
                        case 6:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(26, 27);
                            break;
                        case 9:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 88)
                                kind = 88;
                            jjCheckNAddStates(23, 25);
                            break;
                        case 10:
                            if ((0x7ffffff87fffffeL & l) == 0L)
                                break;
                            if (kind > 88)
                                kind = 88;
                            jjCheckNAdd(10);
                            break;
                        case 11:
                            if ((0x7fffffe87fffffeL & l) != 0L)
                                jjCheckNAddTwoStates(11, 12);
                            break;
                        case 13:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 92)
                                kind = 92;
                            jjstateSet[jjnewStateCnt++] = 13;
                            break;
                        case 17:
                            if (curChar == 76 && kind > 94)
                                kind = 94;
                            break;
                        case 21:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(28, 29);
                            break;
                        case 25:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(30, 31);
                            break;
                        case 29:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(32, 33);
                            break;
                        case 33:
                            jjCheckNAddStates(17, 19);
                            break;
                        case 36:
                            jjCheckNAddStates(20, 22);
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else {
                int hiByte = (int) (curChar >> 8);
                int i1 = hiByte >> 6;
                long l1 = 1L << (hiByte & 077);
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 33:
                            if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                                jjCheckNAddStates(17, 19);
                            break;
                        case 36:
                            if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                                jjCheckNAddStates(20, 22);
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 49 - (jjnewStateCnt = startsAt)))
                break;
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                break;
            }
        }
        if (jjmatchedPos > strPos)
            return curPos;

        int toRet = Math.max(curPos, seenUpto);

        if (curPos < toRet)
            for (i = toRet - Math.min(curPos, seenUpto); i-- > 0; )
                try {
                    curChar = input_stream.readChar();
                } catch (java.io.IOException e) {
                    throw new Error("Internal Error : Please send a bug report.");
                }

        if (jjmatchedPos < strPos) {
            jjmatchedKind = strKind;
            jjmatchedPos = strPos;
        } else if (jjmatchedPos == strPos && jjmatchedKind > strKind)
            jjmatchedKind = strKind;

        return toRet;
    }

    static final int[] jjnextStates = {
            15, 16, 17, 18, 19, 24, 25, 28, 29, 33, 35, 37, 38, 2, 3, 11,
            12, 33, 35, 37, 35, 36, 37, 10, 11, 12, 7, 8, 22, 23, 26, 27,
            30, 31,
    };

    private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2) {
        switch (hiByte) {
            case 0:
                return ((jjbitVec2[i2] & l2) != 0L);
            default:
                if ((jjbitVec0[i1] & l1) != 0L)
                    return true;
                return false;
        }
    }

    /**
     * Token literal values.
     */
    public static final String[] jjstrLiteralImages = {
            "", null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, null, null, null, null, null, null, null, null, null, null, null, null,
            null, null, "\72\75", "\174\174", "\73", "\56", "\45\122\117\127\124\131\120\105",
            "\176", "\74", "\74\75", "\76", "\76\75", "\75", "\41\75", "\74\76", "\50\53\51",
            "\50", "\51", "\133", "\135", "\52", "\57", "\53", "\55", "\77", "\173", "\175",
            "\133\52\135", "\54", "\44",};

    /**
     * Lexer state names.
     */
    public static final String[] lexStateNames = {
            "DEFAULT",
    };
    static final long[] jjtoToken = {
            0xffffffffffffffe1L, 0x7ffffffef3ffffffL,
    };
    static final long[] jjtoSkip = {
            0x1eL, 0x0L,
    };
    protected SimpleCharStream input_stream;
    private final int[] jjrounds = new int[49];
    private final int[] jjstateSet = new int[98];
    protected char curChar;

    /**
     * Constructor.
     */
    public SqlParserTokenManager(SimpleCharStream stream) {
        if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
        input_stream = stream;
    }

    /**
     * Constructor.
     */
    public SqlParserTokenManager(SimpleCharStream stream, int lexState) {
        this(stream);
        SwitchTo(lexState);
    }

    /**
     * Reinitialise parser.
     */
    public void ReInit(SimpleCharStream stream) {
        jjmatchedPos = jjnewStateCnt = 0;
        curLexState = defaultLexState;
        input_stream = stream;
        ReInitRounds();
    }

    private void ReInitRounds() {
        int i;
        jjround = 0x80000001;
        for (i = 49; i-- > 0; )
            jjrounds[i] = 0x80000000;
    }

    /**
     * Reinitialise parser.
     */
    public void ReInit(SimpleCharStream stream, int lexState) {
        ReInit(stream);
        SwitchTo(lexState);
    }

    /**
     * Switch to specified lex state.
     */
    public void SwitchTo(int lexState) {
        if (lexState >= 1 || lexState < 0)
            throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
        else
            curLexState = lexState;
    }

    protected Token jjFillToken() {
        final Token t;
        final String curTokenImage;
        final int beginLine;
        final int endLine;
        final int beginColumn;
        final int endColumn;
        String im = jjstrLiteralImages[jjmatchedKind];
        curTokenImage = (im == null) ? input_stream.GetImage() : im;
        beginLine = input_stream.getBeginLine();
        beginColumn = input_stream.getBeginColumn();
        endLine = input_stream.getEndLine();
        endColumn = input_stream.getEndColumn();
        t = Token.newToken(jjmatchedKind, curTokenImage);

        t.beginLine = beginLine;
        t.endLine = endLine;
        t.beginColumn = beginColumn;
        t.endColumn = endColumn;

        return t;
    }

    int curLexState = 0;
    int defaultLexState = 0;
    int jjnewStateCnt;
    int jjround;
    int jjmatchedPos;
    int jjmatchedKind;

    /**
     * Get the next Token.
     */
    public Token getNextToken() {
        Token matchedToken;
        int curPos = 0;

        EOFLoop:
        for (; ; ) {
            try {
                curChar = input_stream.BeginToken();
            } catch (java.io.IOException e) {
                jjmatchedKind = 0;
                matchedToken = jjFillToken();
                return matchedToken;
            }

            jjmatchedKind = 0x7fffffff;
            jjmatchedPos = 0;
            curPos = jjMoveStringLiteralDfa0_0();
            if (jjmatchedKind != 0x7fffffff) {
                if (jjmatchedPos + 1 < curPos)
                    input_stream.backup(curPos - jjmatchedPos - 1);
                if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
                    matchedToken = jjFillToken();
                    return matchedToken;
                } else {
                    continue EOFLoop;
                }
            }
            int error_line = input_stream.getEndLine();
            int error_column = input_stream.getEndColumn();
            String error_after = null;
            boolean EOFSeen = false;
            try {
                input_stream.readChar();
                input_stream.backup(1);
            } catch (java.io.IOException e1) {
                EOFSeen = true;
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
                if (curChar == '\n' || curChar == '\r') {
                    error_line++;
                    error_column = 0;
                } else
                    error_column++;
            }
            if (!EOFSeen) {
                input_stream.backup(1);
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
            }
            throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
        }
    }

    private void jjCheckNAdd(int state) {
        if (jjrounds[state] != jjround) {
            jjstateSet[jjnewStateCnt++] = state;
            jjrounds[state] = jjround;
        }
    }

    private void jjAddStates(int start, int end) {
        do {
            jjstateSet[jjnewStateCnt++] = jjnextStates[start];
        } while (start++ != end);
    }

    private void jjCheckNAddTwoStates(int state1, int state2) {
        jjCheckNAdd(state1);
        jjCheckNAdd(state2);
    }

    private void jjCheckNAddStates(int start, int end) {
        do {
            jjCheckNAdd(jjnextStates[start]);
        } while (start++ != end);
    }

}
